name: app
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./www/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./www/html/index.html:/var/www/html/www/index.html
      - ./www/html/blog.html:/var/www/html/blog/blog.html
    networks:
      - dmz
  api:
    image: php:8.3-fpm
    volumes:
      - ./www/html/products.php:/var/www/html/www/products.php
    env_file:
      - db.env
    command: bash -c "docker-php-ext-install mysqli && php-fpm"
    networks:
      - db_net
      - dmz
  db:
    image: mariadb
    env_file:
      - root.env
      - db.env
    volumes:
      - ./woodytoys.sql:/docker-entrypoint-initdb.d/woodytoys.sql
    networks:
      - db_net
networks:
  dmz:
    ipam:
      config:
        - subnet: 172.20.0.0/16
  db_net:
    ipam: 
      config:
        - subnet: 172.21.0.0/16
