name: app
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./www/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./www/html/index.html:/var/www/html/www/index.html
      - ./www/html/blog.html:/var/www/html/blog/blog.html
    networks:
      app_network:
        ipv4_address: 172.20.0.3
  api:
    image: php:8.3-fpm
    volumes:
      - ./www/html/products.php:/var/www/html/www/products.php
    command: bash -c "docker-php-ext-install mysqli && php-fpm"
    networks:
      app_network:
        ipv4_address: 172.20.0.4
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_DATABASE=woodytoys
    volumes:
      - ./woodytoys.sql:/docker-entrypoint-initdb.d/woodytoys.sql
    networks:
      app_network:
        ipv4_address: 172.20.0.5

networks:
  app_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
